### ISSUE TITLE
langnhinemkhoc

### ISSUE THREAD

**Issue by langnhinemkhoc** [HieuTranTrung1204/TrainingCocos2dx#9]
![1](https://user-images.githubusercontent.com/38359576/40846808-d3863fbe-65e4-11e8-9f91-512fda107b69.png)
[321.txt](https://github.com/HieuTranTrung1204/TrainingCocos2dx/files/2063078/321.txt)

**Comment by trunghieuvn** [comment]
Trong log em đang sài r17 mới nhất do tích hợp chung android sdk,  k tương thích vs version cocos2dx em đang sài hiện tại 
-> em download ndk r14 về rồi trỏ lại
